### ISSUE TITLE
指纹不够灵活

### ISSUE THREAD

**Issue by jingyuexing** [lcvvvv/gonmap#10]
看了一下,指纹都是写死的,并不是一些配置文件,端口也不一定是指纹当中的服务
我的想法是 先用快速扫描扫描主机端口,比如半开放扫描 只发送握手包之类的,去判定一个端口有没有开放,只有扫描到端口开放了,才建立完整链接,然后把响应报文送到指纹匹配的模块当中
nmap很多指纹都是用的外部的配置文件配置的,还有比如用于HTTP指纹的wappalyzer 也有一堆指纹,这些都可以进行用来配置扫描器的

**Comment by lcvvvv** [comment]
这是gonmap库，负责go来实现nmap功能
其他功能转隔壁kscan
半开连接扫描转隔壁gomasscan
