### ISSUE TITLE
gonmap_test.go可以完善下吗？

### ISSUE THREAD

**Issue by i11us0ry** [lcvvvv/gonmap#3]
师傅，gonmap_test.go中的例子可以完善下吗，比如如何单独调用TestPortscan等，感谢

**Comment by lcvvvv** [comment]
蛤，还真没想到这个也有人看，隔壁kscan有详细的调用案例，这个库的案例有空我写写吧，最近太忙了

**Comment by i11us0ry** [comment]
嗯嗯，辛苦师傅了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月19日(周一) 晚上8:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lcvvvv/gonmap] gonmap_test.go可以完善下吗？ (#3)




 
蛤，还真没想到这个也有人看，隔壁kscan有详细的调用案例，这个库的案例有空我写写吧，最近太忙了

**Comment by i11us0ry** [comment]
gonmap.Init(5,5 * time.Second)
	netloc := "39.106.2.45:6379"
	r := gonmap.GetTcpBanner(netloc, gonmap.New(), 10 * time.Second)
	fmt.Println(r)
	
调用tcpbanner如上，之前一直失败是因为第三个参数没加 * time.Second，导致最终传过去的时间为10ns，所以一直失败，现在可以调用了，看来我还得继续努力才行，感谢师傅提供的案例。
