### ISSUE TITLE
misc.go中的Xrange方法bug

### ISSUE THREAD

**Issue by lal0ne** [lcvvvv/gonmap#5]
位置：[https://github.com/lcvvvv/gonmap/blob/dbc21b8462c2b565651bf64951631b32689ba82d/misc.go#L39](https://github.com/lcvvvv/gonmap/blob/dbc21b8462c2b565651bf64951631b32689ba82d/misc.go#L39)
是否应为 `start, stop, step = args[0], args[1], args[2]`

**Comment by lcvvvv** [comment]
已修改
